// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_oddVhaMpCIYQq97PpHiRSpnULYLR1rE',
    appId: '1:645295703411:web:03fc7e3110d20926caf106',
    messagingSenderId: '645295703411',
    projectId: 'yazilim-toplulugu-app',
    authDomain: 'yazilim-toplulugu-app.firebaseapp.com',
    storageBucket: 'yazilim-toplulugu-app.firebasestorage.app',
    measurementId: 'G-ZJMQ3HM7JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPU7OPt8MpWJ4Jpx0mOJAe8Zjq8HfzvuI',
    appId: '1:645295703411:android:9b7b0ee11c9c3822caf106',
    messagingSenderId: '645295703411',
    projectId: 'yazilim-toplulugu-app',
    storageBucket: 'yazilim-toplulugu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOooxauA-xCS_BsuSHjYXz0sJ4wwfx-fw',
    appId: '1:645295703411:ios:d0260aa5231b2afdcaf106',
    messagingSenderId: '645295703411',
    projectId: 'yazilim-toplulugu-app',
    storageBucket: 'yazilim-toplulugu-app.firebasestorage.app',
    iosBundleId: 'com.denizbaranaykul.yazilimTopluluguApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOooxauA-xCS_BsuSHjYXz0sJ4wwfx-fw',
    appId: '1:645295703411:ios:d0260aa5231b2afdcaf106',
    messagingSenderId: '645295703411',
    projectId: 'yazilim-toplulugu-app',
    storageBucket: 'yazilim-toplulugu-app.firebasestorage.app',
    iosBundleId: 'com.denizbaranaykul.yazilimTopluluguApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_oddVhaMpCIYQq97PpHiRSpnULYLR1rE',
    appId: '1:645295703411:web:90e8d5354dea993ccaf106',
    messagingSenderId: '645295703411',
    projectId: 'yazilim-toplulugu-app',
    authDomain: 'yazilim-toplulugu-app.firebaseapp.com',
    storageBucket: 'yazilim-toplulugu-app.firebasestorage.app',
    measurementId: 'G-S9RPYGNV72',
  );

}